// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import Header from '../compontes/header'
// import Footer from '../compontes/footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
//   params:{locale},
// }: {
//   children: React.ReactNode;
//   params:{
//     locale:String
//   }
// }) {
//   return (
//     <html lang={locale} dir="rtl">
//       <body className={inter.className}>
//         <Header />
//         {children}
//         <Footer/>
//       </body>
//     </html>
//   )
// }




import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from './compontes/header'
import Footer from './compontes/footer'
import {useLocale} from 'next-intl';
import Navpar from './compontes/Navpar'
import { DarkProvider } from '../themeProvider';
import { Suspense } from 'react';
import Loading from './loading';

// تهيئة خيارات الخط
const inter = Inter({ subsets: ['latin'] })

// تعريف نوع البيانات للميتاداتا
export const metadata: Metadata = {
  title: 'Shopping cart',
  description: 'Generated by create next app',
}

// تعريف النوع للمكون
interface RootLayoutProps {
  children: React.ReactNode;
  locale: string;
}

// تعريف المكون الأساسي
export default function RootLayout({ children, locale }: RootLayoutProps) {


  const local=useLocale()
  
  return (
    <html lang={locale} dir={local==="ar"?'rtl':'ltr'}>
      <body className={inter.className}>
      <DarkProvider>

        <Navpar />
        <Suspense fallback={<Loading/>}>
        {children}
        </Suspense>
        <Footer />


      </DarkProvider>
      </body>
    </html>
  )
}
